// GENERATED by scripts/build.mjs — edit src/ instead of this file.
"use strict";

// src/client/api.ts
async function api(path, body) {
  const init = body ? { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) } : { method: "GET" };
  const res = await fetch("/my-plugins" + path, init);
  const data = await res.json().catch(() => ({ ok: false, message: `${res.status} ${res.statusText}` }));
  if (!res.ok || data.ok === false) {
    throw new Error(data.message || res.statusText);
  }
  return data;
}

// src/client/component.ts
var PHASE_TEXT = {
  pending: "phasePending",
  loading: "phaseLoading",
  active: "phaseActive",
  failed: "phaseFailed",
  unloading: "phaseUnloading"
};
function createMyPluginsTab(React) {
  const { createElement: h, useState, useEffect, useRef } = React;
  function phaseText(phase, t) {
    return t(phase ? PHASE_TEXT[phase] || "phaseUnobserved" : "phaseUnobserved");
  }
  function MyPluginsTab(props) {
    const t = props.t;
    const [plugins, setPlugins] = useState(null);
    const [error, setError] = useState("");
    const [notice, setNotice] = useState(null);
    const [noticeLeaving, setNoticeLeaving] = useState(false);
    const [busy, setBusy] = useState({});
    const [modal, setModal] = useState(null);
    const pollTimer = useRef(null);
    const [expanded, setExpanded] = useState(null);
    const [restarted, setRestarted] = useState(false);
    const refresh = () => {
      setError("");
      setPlugins(null);
      api("/list").then((data) => setPlugins(data.plugins ?? [])).catch((err) => {
        setError(String(err?.message ?? err));
        setPlugins([]);
      });
    };
    useEffect(() => {
      refresh();
    }, []);
    useEffect(() => {
      if (!notice) return void 0;
      setNoticeLeaving(false);
      const timer = setTimeout(
        () => setNoticeLeaving(true),
        notice.kind === "ok" || notice.kind === "warn" ? 4e3 : 8e3
      );
      return () => clearTimeout(timer);
    }, [notice]);
    useEffect(() => {
      if (!noticeLeaving) return void 0;
      const gone = setTimeout(() => setNotice(null), 240);
      return () => clearTimeout(gone);
    }, [noticeLeaving]);
    useEffect(
      () => () => {
        if (pollTimer.current) clearInterval(pollTimer.current);
      },
      []
    );
    const withBusy = (key, fn) => {
      setBusy((current) => ({ ...current, [key]: true }));
      return Promise.resolve().then(fn).catch((err) => {
        setNotice({ kind: "err", text: `${t("opFailed")}\uFF1A${err?.message ?? err}` });
      }).finally(() => {
        setBusy((current) => ({ ...current, [key]: false }));
        setModal(null);
      });
    };
    const toggle = (pkg) => {
      const row = (plugins ?? []).find((p) => p.pkg === pkg);
      if (!row) return;
      const enabled = !row.enabled;
      return withBusy(
        pkg,
        () => api("/set-enabled", { pkg, enabled }).then(() => {
          setNotice({
            kind: enabled ? "ok" : "warn",
            text: enabled ? t("enabledDone") : t("disabledDone")
          });
          refresh();
        })
      );
    };
    const uninstallRow = (pkg) => withBusy(
      pkg,
      () => api("/uninstall", { pkg }).then(() => {
        setNotice({ kind: "ok", text: t("removed").replace("{pkg}", pkg) });
        refresh();
      })
    );
    const doRestart = () => withBusy(
      "__restart__",
      () => api("/restart", {}).then(() => {
        setRestarted(true);
        setNotice({ kind: "info", text: t("restarting") });
        let attempts = 0;
        let okStreak = 0;
        pollTimer.current = setInterval(() => {
          attempts += 1;
          fetch(`/my-plugins/list?_=${Date.now()}`).then((res) => {
            if (res.ok) {
              okStreak += 1;
              if (okStreak >= 3) {
                clearInterval(pollTimer.current);
                location.reload();
              }
            } else {
              okStreak = 0;
              if (attempts >= 80) {
                clearInterval(pollTimer.current);
                setNotice({ kind: "err", text: t("restartTimeout") });
              }
            }
          }).catch(() => {
            okStreak = 0;
            if (attempts >= 80) {
              clearInterval(pollTimer.current);
              setNotice({ kind: "err", text: t("restartTimeout") });
            }
          });
        }, 1500);
      })
    );
    const card = (row) => {
      const open = expanded === row.pkg;
      const busyKey = busy[row.pkg];
      const tag = row.enabled ? t("enabledTag") : t("disabledTag");
      return h(
        "li",
        { className: "mp-card", "data-open": open ? "true" : void 0, key: row.pkg },
        h(
          "button",
          {
            className: "mp-cardContent",
            type: "button",
            "aria-expanded": open,
            onClick: () => setExpanded((current) => current === row.pkg ? null : row.pkg)
          },
          h("strong", { className: "mp-cardTitle", title: row.pkg }, row.pkg),
          h(
            "span",
            { className: "mp-cardTrailing" },
            // like the official list: the status dot renders only when enabled
            row.enabled ? h("span", {
              className: "mp-statusDot",
              "data-phase": row.fiberPhase || "unobserved",
              role: "img",
              title: phaseText(row.fiberPhase, t)
            }) : null,
            h(
              "span",
              { className: "mp-configTag", "data-enabled": row.enabled ? "true" : "false" },
              tag
            ),
            h(
              "svg",
              {
                className: "mp-chevron",
                width: 12,
                height: 12,
                viewBox: "0 0 14 14",
                fill: "none",
                "aria-hidden": "true"
              },
              h("path", {
                d: "M3.5 5.5 7 9l3.5-3.5",
                stroke: "currentColor",
                strokeWidth: "1.5",
                strokeLinecap: "round",
                strokeLinejoin: "round"
              })
            )
          )
        ),
        open ? h(
          "div",
          { className: "mp-cardDetails" },
          h("code", { className: "mp-entryValue" }, row.entryId),
          h(
            "dl",
            { className: "mp-details" },
            h("div", null, h("dt", null, t("version")), h("dd", null, row.version)),
            h("div", null, h("dt", null, t("configuration")), h("dd", null, tag)),
            row.enabled ? h("div", null, h("dt", null, t("cordis")), h("dd", null, phaseText(row.fiberPhase, t))) : null,
            row.patchDisabled ? h("div", null, h("dt", null, t("persist")), h("dd", null, t("persistedYes"))) : null
          ),
          h(
            "div",
            { className: "mp-actions" },
            row.pkg === "dsh-my-plugins" ? h("span", { className: "mp-status" }, t("selfDisable")) : h(
              "button",
              {
                className: "mp-btn",
                type: "button",
                disabled: !!busyKey || restarted,
                onClick: () => toggle(row.pkg)
              },
              row.enabled ? t("disable") : t("enable")
            ),
            h(
              "button",
              {
                className: "mp-btn mp-danger",
                type: "button",
                disabled: !!busyKey || restarted,
                onClick: () => setModal({ kind: "uninstall", pkg: row.pkg })
              },
              t("uninstall")
            )
          )
        ) : null
      );
    };
    let body;
    if (plugins === null) {
      body = h("p", { className: "mp-status" }, t("loading"));
    } else if (error) {
      body = h("p", { className: "mp-status" }, t("error"), " \u2014 ", error);
    } else if (!plugins.length) {
      body = h("p", { className: "mp-status" }, t("empty"));
    } else {
      body = h("ul", { className: "mp-cards" }, plugins.map(card));
    }
    return h(
      "div",
      null,
      h(
        "div",
        { className: "mp-toolbar" },
        h(
          "button",
          { className: "mp-btn", type: "button", disabled: restarted, onClick: () => refresh() },
          t("refresh")
        ),
        h("span", { className: "mp-spacer" }),
        h(
          "button",
          {
            className: "mp-btn mp-danger",
            type: "button",
            disabled: restarted,
            onClick: () => setModal({ kind: "restart" })
          },
          t("restart")
        )
      ),
      notice ? h(
        "div",
        { className: "mp-toastWrap" },
        h(
          "div",
          {
            className: `mp-toast mp-${notice.kind}${noticeLeaving ? " mp-out" : " mp-in"}`,
            role: "status",
            key: `${notice.kind}:${notice.text}`
          },
          h("span", { className: "mp-toastDot", "aria-hidden": "true" }),
          h("span", { className: "mp-toastText" }, notice.text),
          h(
            "button",
            {
              className: "mp-toastClose",
              type: "button",
              "aria-label": t("close"),
              onClick: () => setNoticeLeaving(true)
            },
            "\xD7"
          )
        )
      ) : null,
      h("p", { className: "mp-hint" }, t("hint")),
      body,
      modal ? h(
        "div",
        { className: "mp-overlay", onClick: () => setModal(null) },
        h(
          "div",
          {
            className: "mp-dialog",
            onClick: (ev) => ev.stopPropagation()
          },
          h(
            "h3",
            { className: "mp-dialogTitle" },
            modal.kind === "restart" ? t("restart") : `${t("uninstall")} \u2014 ${modal.pkg}`
          ),
          h(
            "p",
            { className: "mp-dialogBody" },
            modal.kind === "restart" ? t("confirmRestart") : t("uninstallConfirm").replace("{pkg}", modal.pkg)
          ),
          h(
            "div",
            { className: "mp-dialogActions" },
            h(
              "button",
              { className: "mp-btn", type: "button", onClick: () => setModal(null) },
              t("cancel")
            ),
            h(
              "button",
              {
                className: "mp-btn mp-confirm",
                type: "button",
                onClick: () => {
                  const m = modal;
                  setModal(null);
                  if (m.kind === "restart") return doRestart();
                  return uninstallRow(m.pkg);
                }
              },
              t("confirmOk")
            )
          )
        )
      ) : null
    );
  }
  return MyPluginsTab;
}

// src/client/locales.ts
var zh = {
  tab: "\u6211\u7684\u63D2\u4EF6",
  hint: "\u8FD9\u91CC\u53EA\u663E\u793A\u4F60\u81EA\u5DF1\u5B89\u88C5\u7684\u63D2\u4EF6\uFF08\u6309 profile \u4F9D\u8D56\u8BC6\u522B\uFF09\uFF1B\u5B98\u65B9\u81EA\u5E26\u63D2\u4EF6\u4E0D\u5728\u6B64\u7BA1\u7406\u3002",
  refresh: "\u5237\u65B0",
  restart: "\u91CD\u542F dsh web",
  confirmRestart: "\u786E\u5B9A\u8981\u91CD\u542F dsh web \u5417\uFF1F\u5F53\u524D\u9875\u9762\u8FDE\u63A5\u4F1A\u6682\u65F6\u65AD\u5F00\uFF0C\u91CD\u542F\u5B8C\u6210\u540E\u8BF7\u624B\u52A8\u5237\u65B0\u9875\u9762\u3002",
  restarting: "\u6B63\u5728\u91CD\u542F\u2026\u2026\u670D\u52A1\u5668\u6062\u590D\u540E\u672C\u9875\u4F1A\u81EA\u52A8\u5237\u65B0\u3002",
  enable: "\u542F\u7528",
  disable: "\u5173\u95ED",
  uninstall: "\u5378\u8F7D",
  cancel: "\u53D6\u6D88",
  confirmOk: "\u786E\u5B9A",
  close: "\u5173\u95ED",
  uninstallConfirm: "\u786E\u5B9A\u8981\u5378\u8F7D {pkg} \u5417\uFF1F\u5378\u8F7D\u540E\u9700\u91CD\u542F dsh web \u624D\u80FD\u5B8C\u5168\u751F\u6548\u3002",
  restartTimeout: "\u670D\u52A1\u5668 2 \u5206\u949F\u5185\u672A\u6062\u590D\uFF0C\u8BF7\u624B\u52A8\u5237\u65B0\u9875\u9762\u3002",
  enabledTag: "\u5DF2\u542F\u7528",
  disabledTag: "\u5DF2\u505C\u7528",
  configuration: "\u914D\u7F6E\u72B6\u6001",
  cordis: "Cordis \u72B6\u6001",
  persist: "\u6301\u4E45\u5316",
  persistedYes: "\u5DF2\u5199\u5165\u8865\u4E01\u5C42\uFF0C\u91CD\u542F\u540E\u4FDD\u6301\u5173\u95ED",
  phaseUnobserved: "\u672A\u6302\u8F7D",
  phasePending: "\u7B49\u5F85\u4F9D\u8D56",
  phaseLoading: "\u52A0\u8F7D\u4E2D",
  phaseActive: "\u5DF2\u6302\u8F7D",
  phaseFailed: "\u6302\u8F7D\u5931\u8D25",
  phaseUnloading: "\u5378\u8F7D\u4E2D",
  needsRestartTag: "\u5DF2\u5378\u8F7D\xB7\u9700\u91CD\u542F",
  loading: "\u52A0\u8F7D\u4E2D\u2026",
  empty: "\u4F60\u8FD8\u6CA1\u6709\u5B89\u88C5\u4EFB\u4F55\u63D2\u4EF6\u3002\u5B89\u88C5\u65B9\u5F0F\uFF1Adsh plugin --profile web add <\u5305\u540D>\u3002",
  error: "\u52A0\u8F7D\u5931\u8D25",
  version: "\u7248\u672C",
  entry: "\u6761\u76EE",
  patchPersisted: "\u5173\u95ED\u72B6\u6001\u5DF2\u6301\u4E45\u5316\uFF08\u91CD\u542F dsh web \u540E\u4ECD\u4FDD\u6301\u5173\u95ED\uFF09",
  opDone: "\u5DF2\u5B8C\u6210",
  enabledDone: "\u5DF2\u542F\u7528",
  disabledDone: "\u5DF2\u5173\u95ED",
  opFailed: "\u64CD\u4F5C\u5931\u8D25",
  removed: "\u5DF2\u5378\u8F7D {pkg}\uFF0C\u91CD\u542F dsh web \u540E\u5B8C\u5168\u751F\u6548\u3002",
  builtin: "\u5B98\u65B9\u81EA\u5E26\u63D2\u4EF6",
  selfDisable: "\u9762\u677F\u81EA\u8EAB\u4E0D\u80FD\u5728\u8FD9\u91CC\u5173\u95ED\uFF08\u82E5\u8981\u505C\u7528\u8BF7\u5378\u8F7D\u6216\u76F4\u63A5\u7528\u547D\u4EE4\u884C\u7BA1\u7406\uFF09"
};
var en = {
  tab: "My plugins",
  hint: "Only plugins you installed are listed here (detected from profile dependencies). Built-in bundles are not managed.",
  refresh: "Refresh",
  restart: "Restart dsh web",
  confirmRestart: "Restart dsh web now? The page connection will drop; refresh the page once it is back.",
  restarting: "Restarting\u2026 this page will reload automatically once the server is back.",
  enable: "Enable",
  disable: "Disable",
  uninstall: "Uninstall",
  cancel: "Cancel",
  confirmOk: "Confirm",
  close: "Close",
  uninstallConfirm: "Uninstall {pkg}? It takes full effect after restarting dsh web.",
  restartTimeout: "The server did not come back within 2 minutes. Please refresh manually.",
  enabledTag: "Enabled",
  disabledTag: "Disabled",
  configuration: "Configuration",
  cordis: "Cordis status",
  persist: "Persisted",
  persistedYes: "Written to the patch layer; stays disabled after restart",
  phaseUnobserved: "Not mounted",
  phasePending: "Waiting for dependencies",
  phaseLoading: "Loading",
  phaseActive: "Mounted",
  phaseFailed: "Mount failed",
  phaseUnloading: "Unloading",
  needsRestartTag: "Removed \xB7 restart needed",
  loading: "Loading\u2026",
  empty: "You have not installed any plugins yet. Install with: dsh plugin --profile web add <package>.",
  error: "Load failed",
  version: "Version",
  entry: "Entry",
  patchPersisted: "Disabled state persisted (stays disabled after dsh web restarts)",
  opDone: "Done",
  enabledDone: "Enabled",
  disabledDone: "Disabled",
  opFailed: "Operation failed",
  removed: "{pkg} uninstalled; takes full effect after restarting dsh web.",
  builtin: "Built-in plugins",
  selfDisable: "This panel cannot disable itself here (uninstall or use the CLI instead)"
};

// src/client/styles.ts
var CSS = [
  // ---- hint / toolbar / buttons (theme variables) ----
  ".mp-hint{color:var(--dsw-alias-label-tertiary);font-size:13px;line-height:20px;margin:0 0 12px}",
  ".mp-toolbar{display:flex;gap:8px;margin:0 0 12px;flex-wrap:wrap}",
  ".mp-toolbar .mp-spacer{flex:1}",
  ".mp-btn{display:inline-flex;align-items:center;gap:6px;padding:4px 12px;border-radius:6px;border:1px solid var(--dsw-alias-border-l2);background:transparent;color:var(--dsw-alias-label-primary);font:inherit;font-size:13px;cursor:pointer;line-height:1.6}",
  ".mp-btn:hover:not(:disabled){background:var(--dsw-alias-interactive-bg-hover)}",
  ".mp-btn:disabled{opacity:.45;cursor:not-allowed}",
  ".mp-btn.mp-danger{color:var(--dsw-alias-state-error-primary);border-color:color-mix(in srgb, var(--dsw-alias-state-error-primary) 45%, transparent)}",
  ".mp-btn.mp-danger:hover:not(:disabled){background:color-mix(in srgb, var(--dsw-alias-state-error-primary) 12%, transparent)}",
  ".mp-btn.mp-confirm{background:var(--dsw-alias-state-error-primary);border-color:var(--dsw-alias-state-error-primary);color:#fff}",
  ".mp-btn.mp-confirm:hover:not(:disabled){background:color-mix(in srgb, var(--dsw-alias-state-error-primary) 85%, #000)}",
  // ---- toast notifications (floating, no layout impact) ----
  ".mp-toastWrap{position:fixed;top:18px;left:50%;transform:translateX(-50%);z-index:1100;display:flex;flex-direction:column;align-items:center;gap:8px;pointer-events:none}",
  ".mp-toast{pointer-events:auto;display:flex;align-items:center;gap:8px;max-width:min(560px,calc(100vw - 48px));padding:8px 10px 8px 12px;border-radius:10px;border:1px solid var(--dsw-alias-border-l1);background:var(--dsw-alias-bg-layer-3);color:var(--dsw-alias-label-secondary);font-size:13px;line-height:20px;box-shadow:var(--dsw-shadow-lv1)}",
  ".mp-toast.mp-ok{border-color:color-mix(in srgb, var(--dsw-alias-state-success-primary) 40%, transparent)}",
  ".mp-toast.mp-err{border-color:color-mix(in srgb, var(--dsw-alias-state-error-primary) 45%, transparent);color:var(--dsw-alias-state-error-primary)}",
  ".mp-toast.mp-warn{border-color:color-mix(in srgb, var(--dsw-alias-state-warning-primary, #d97706) 45%, transparent);color:var(--dsw-alias-state-warning-primary, #b45309)}",
  ".mp-toast.mp-warn .mp-toastDot{background:var(--dsw-alias-state-warning-primary, #d97706)}",
  ".mp-toast.mp-info{color:var(--dsw-alias-label-secondary)}",
  ".mp-toast.mp-info .mp-toastDot{background:var(--dsw-alias-label-tertiary)}",
  ".mp-toastDot{flex:none;width:7px;height:7px;border-radius:999px;background:var(--dsw-alias-state-success-primary)}",
  ".mp-toast.mp-err .mp-toastDot{background:var(--dsw-alias-state-error-primary)}",
  ".mp-toastText{word-break:break-word}",
  ".mp-toastClose{flex:none;display:inline-flex;align-items:center;justify-content:center;width:20px;height:20px;margin-left:2px;padding:0;border:0;border-radius:6px;background:transparent;color:var(--dsw-alias-label-tertiary);font-size:14px;line-height:1;cursor:pointer}",
  ".mp-toastClose:hover{background:var(--dsw-alias-interactive-bg-hover);color:var(--dsw-alias-label-primary)}",
  "@media (prefers-reduced-motion:no-preference){.mp-toast.mp-in{animation:mp-toast-in .22s var(--ds-ease-in-out)}.mp-toast.mp-out{animation:mp-toast-out .2s var(--ds-ease-in-out) forwards}}",
  "@keyframes mp-toast-in{from{opacity:0;transform:translateY(-10px)}to{opacity:1;transform:translateY(0)}}",
  "@keyframes mp-toast-out{from{opacity:1}to{opacity:0;transform:translateY(-10px)}}",
  // ---- cards (same variables/structure as the official invlist) ----
  ".mp-cards{list-style:none;margin:0;padding:0;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));align-items:start;gap:10px}",
  ".mp-card{border:1px solid var(--dsw-alias-border-l2);background:var(--dsw-alias-bg-layer-3);border-radius:10px;min-width:0;overflow:hidden}",
  ".mp-card[data-open=true]{border-color:var(--dsw-alias-border-l1);box-shadow:var(--dsw-shadow-lv1)}",
  ".mp-cardContent{box-sizing:border-box;width:100%;min-height:52px;color:inherit;font:inherit;text-align:left;cursor:pointer;background:0 0;border:0;justify-content:space-between;align-items:center;gap:12px;padding:12px 14px;display:flex}",
  ".mp-cardContent:hover,.mp-card[data-open=true]>.mp-cardContent{background:var(--dsw-alias-interactive-bg-hover)}",
  ".mp-cardContent:focus-visible{outline:2px solid var(--dsw-alias-state-business-primary);outline-offset:-2px}",
  ".mp-cardTitle{text-overflow:ellipsis;white-space:nowrap;min-width:0;color:var(--dsw-alias-label-primary);font-size:14px;font-weight:600;line-height:20px;overflow:hidden}",
  ".mp-cardTrailing{color:var(--dsw-alias-label-tertiary);flex:none;align-items:center;gap:7px;display:inline-flex}",
  ".mp-statusDot{background:var(--dsw-alias-label-tertiary);border-radius:999px;flex:none;width:7px;height:7px;display:inline-block}",
  ".mp-statusDot[data-phase=active]{background:var(--dsw-alias-state-success-primary)}",
  ".mp-statusDot[data-phase=failed]{background:var(--dsw-alias-state-error-primary)}",
  ".mp-statusDot[data-phase=loading]{background:var(--dsw-alias-state-business-primary)}",
  ".mp-configTag{background:var(--dsw-alias-bg-layer-1);min-height:20px;color:var(--dsw-alias-label-secondary);white-space:nowrap;border-radius:5px;align-items:center;padding:1px 6px;font-size:11px;line-height:16px;display:inline-flex}",
  ".mp-configTag[data-enabled=true]{background:color-mix(in srgb, var(--dsw-alias-state-success-primary) 10%, transparent);color:var(--dsw-alias-state-success-primary)}",
  ".mp-chevron{color:var(--dsw-alias-label-tertiary);flex:none}",
  ".mp-card[data-open=true] .mp-chevron{transform:rotate(180deg)}",
  "@media (prefers-reduced-motion:no-preference){.mp-chevron{transition:transform .14s var(--ds-ease-in-out)}}",
  ".mp-cardDetails{border-top:1px solid var(--dsw-alias-border-l2);background:var(--dsw-alias-bg-module-platform);padding:10px 14px 12px}",
  ".mp-entryValue{overflow-wrap:anywhere;color:var(--dsw-alias-label-primary);font-family:var(--ds-font-family-code);font-size:12px;line-height:18px;display:block;margin:0 0 6px}",
  ".mp-details{grid-template-columns:76px minmax(0,1fr);gap:6px 10px;margin:0;display:grid}",
  ".mp-details div{display:contents}",
  ".mp-details dt{color:var(--dsw-alias-label-tertiary);font-size:11px;line-height:17px}",
  ".mp-details dd{overflow-wrap:anywhere;min-width:0;color:var(--dsw-alias-label-secondary);margin:0;font-size:12px;line-height:17px}",
  ".mp-actions{display:flex;gap:8px;flex-wrap:wrap;border-top:1px solid var(--dsw-alias-border-l2);margin-top:10px;padding-top:10px}",
  ".mp-status{color:var(--dsw-alias-label-tertiary);font-size:13px;line-height:20px;margin:.5em 0 0;text-align:center}",
  "@media (width<=680px){.mp-cards{grid-template-columns:minmax(0,1fr)}}",
  // ---- modal ----
  ".mp-overlay{position:fixed;inset:0;background:rgba(0,0,0,.45);display:flex;align-items:center;justify-content:center;z-index:1000}",
  ".mp-dialog{background:var(--dsw-alias-bg-layer-3);color:var(--dsw-alias-label-primary);border:1px solid var(--dsw-alias-border-l1);border-radius:10px;padding:18px 20px 14px;max-width:420px;width:calc(100vw - 48px);box-shadow:var(--dsw-shadow-lv1)}",
  ".mp-dialogTitle{margin:0 0 8px;font-size:14px;font-weight:600;line-height:20px}",
  ".mp-dialogBody{margin:0 0 14px;font-size:13px;line-height:1.55;color:var(--dsw-alias-label-secondary);word-break:break-all}",
  ".mp-dialogActions{display:flex;justify-content:flex-end;gap:8px}"
].join("\n");

// src/client/app.ts
var NS = "settings.myPlugins";
var INJECT = ["slots", "locale"];
function createApp(React) {
  const Tab = createMyPluginsTab(React);
  function apply(ctx) {
    ctx.effect(
      () => ctx.locale.register(NS, { zh, en }),
      "my-plugins: dictionaries"
    );
    if (typeof document !== "undefined" && !document.getElementById("mp-style")) {
      const style = document.createElement("style");
      style.id = "mp-style";
      style.textContent = CSS;
      document.head.appendChild(style);
    }
    const t = ctx.locale.bind(NS);
    const injected = () => ({ t });
    ctx.slots.inject(
      "settings.plugins.tab",
      () => ctx.slots.register(
        {
          name: "settings.plugins.tab",
          id: "my-plugins",
          order: 20,
          label: () => t("tab"),
          locale: NS,
          inject: injected
        },
        Tab
      )
    );
  }
  return { NS, apply, inject: INJECT };
}

// src/client/index.ts
function factory(require2) {
  const React = require2("react");
  return createApp(React);
}
if (typeof window !== "undefined" && window.__ModuleLoader__) {
  window.__ModuleLoader__.load({ id: "dsh-my-plugins", factory });
}
