// GENERATED by scripts/build.mjs — edit src/ instead of this file.

// src/host/constants.ts
import { homedir } from "node:os";
import { join } from "node:path";
var NAME = "dsh-my-plugins";
var INJECT = ["loader", "webServer"];
var DSHP = process.env.DSH_HOME || join(homedir(), ".dsh");
var PROFILE = process.env.DSH_PROFILE || "web";
var PROFILE_DIR = join(DSHP, "profiles", PROFILE);
var PROFILE_PKG = join(PROFILE_DIR, "package.json");
var PROFILE_PATCH = join(PROFILE_DIR, "cordis.patch.yml");
var DATA_DIR = join(DSHP, "dsh-my-plugins");
var STATE_FILE = join(DATA_DIR, "state.json");
var AUDIT_FILE = join(DATA_DIR, "audit.jsonl");
var BLOCK_BEGIN = "# dsh-my-plugins managed begin";
var BLOCK_END = "# dsh-my-plugins managed end";
var FIBER_PHASE = {
  0: "pending",
  1: "loading",
  2: "active",
  3: "failed",
  4: "unloading",
  5: null
  // DISPOSED
};

// src/host/patch.ts
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
function patchRowId(id) {
  const segments = String(id).split(":");
  return segments[segments.length - 1];
}
function loadState() {
  try {
    const parsed = JSON.parse(readFileSync(STATE_FILE, "utf8"));
    if (parsed && typeof parsed === "object" && parsed.disabled && typeof parsed.disabled === "object") {
      return parsed;
    }
  } catch {
  }
  return { disabled: {} };
}
function saveState(state) {
  mkdirSync(DATA_DIR, { recursive: true });
  writeFileSync(STATE_FILE, JSON.stringify(state, null, 2) + "\n", { mode: 384 });
}
function renderPatchLayer(state) {
  const ids = Object.keys(state.disabled).filter((id) => state.disabled[id]).sort();
  let existing = "";
  try {
    existing = readFileSync(PROFILE_PATCH, "utf8");
  } catch {
  }
  const head = [];
  for (const line of existing.split("\n")) {
    if (line.includes(BLOCK_BEGIN)) break;
    if (line.trim().startsWith("#")) head.push(line);
  }
  const rows = ids.map((id) => `- id: ${patchRowId(id)}
  disabled: true`);
  const block = rows.length ? [BLOCK_BEGIN, ...rows, BLOCK_END].join("\n") : [BLOCK_BEGIN, "[]", BLOCK_END].join("\n");
  mkdirSync(PROFILE_DIR, { recursive: true });
  writeFileSync(PROFILE_PATCH, [...head, block].join("\n").trimEnd() + "\n");
}

// src/host/audit.ts
import { appendFileSync, mkdirSync as mkdirSync2 } from "node:fs";
function audit(action, extra = {}) {
  try {
    mkdirSync2(DATA_DIR, { recursive: true });
    appendFileSync(
      AUDIT_FILE,
      JSON.stringify({ ts: (/* @__PURE__ */ new Date()).toISOString(), action, ...extra }) + "\n"
    );
  } catch {
  }
}

// src/host/profile.ts
import { readFileSync as readFileSync2 } from "node:fs";
import { join as join2 } from "node:path";
function readProfilePkg() {
  return JSON.parse(readFileSync2(PROFILE_PKG, "utf8"));
}
function userDeps() {
  return Object.keys(readProfilePkg().dependencies ?? {});
}
function installedVersion(pkg) {
  try {
    const pkgJson = JSON.parse(
      readFileSync2(join2(PROFILE_DIR, "node_modules", pkg, "package.json"), "utf8")
    );
    return pkgJson.version ?? "?";
  } catch {
    return "?";
  }
}

// src/host/loader.ts
function findEntryId(loader, pkg) {
  for (const entry of loader.entries()) {
    if (entry.options?.group) continue;
    if (entry.options?.name === pkg) return entry.id;
  }
  return null;
}
function buildList(loader, state) {
  const deps = new Set(userDeps());
  const seen = /* @__PURE__ */ new Set();
  const plugins = [];
  for (const entry of loader.entries()) {
    if (entry.options?.group) continue;
    const moduleName = entry.options?.name ?? "";
    if (!deps.has(moduleName)) continue;
    if (seen.has(moduleName)) continue;
    seen.add(moduleName);
    const rawId = String(entry.id);
    const fiberPhase = entry.fiber === void 0 ? null : FIBER_PHASE[entry.fiber.state ?? -1] ?? null;
    plugins.push({
      pkg: moduleName,
      rawId,
      entryId: patchRowId(rawId),
      enabled: !entry.disabled,
      fiberPhase,
      version: installedVersion(moduleName),
      patchDisabled: !!state.disabled[rawId] || !!state.disabled[patchRowId(rawId)]
    });
  }
  return { plugins };
}

// src/host/operations.ts
import { execFileSync } from "node:child_process";
import { writeFileSync as writeFileSync2 } from "node:fs";
function setEnabled(loader, state, pkg, enabled) {
  if (!userDeps().includes(pkg)) {
    throw new Error(`\u62D2\u7EDD\u64CD\u4F5C\uFF1A${pkg} \u4E0D\u5728\u300C\u4F60\u5B89\u88C5\u7684\u63D2\u4EF6\u300D\u6E05\u5355\u91CC`);
  }
  if (pkg === NAME) {
    throw new Error(
      "\u300C\u6211\u7684\u63D2\u4EF6\u300D\u9762\u677F\u4E0D\u80FD\u5173\u95ED\u81EA\u8EAB\uFF08\u4F1A\u88AB\u6301\u4E45\u5316\u4E3A disabled\uFF0C\u65E0\u6CD5\u518D\u4ECE\u754C\u9762\u6062\u590D\uFF09"
    );
  }
  const entryId = findEntryId(loader, pkg);
  if (!entryId) {
    throw new Error(`\u8FD0\u884C\u65F6\u6761\u76EE\u672A\u627E\u5230\uFF1A${pkg}\uFF08\u53EF\u80FD\u672A\u88AB loader \u8F7D\u5165\uFF09`);
  }
  loader.update(entryId, { disabled: !enabled });
  if (enabled) {
    delete state.disabled[entryId];
    delete state.disabled[pkg];
  } else {
    state.disabled[entryId] = true;
  }
  saveState(state);
  renderPatchLayer(state);
  audit(enabled ? "enable" : "disable", { pkg, entryId });
  return { pkg, entryId: patchRowId(entryId), enabled, disabled: !enabled };
}
function uninstallPackage(loader, state, pkg) {
  if (!userDeps().includes(pkg)) {
    throw new Error(`\u62D2\u7EDD\u64CD\u4F5C\uFF1A${pkg} \u4E0D\u5728\u300C\u4F60\u5B89\u88C5\u7684\u63D2\u4EF6\u300D\u6E05\u5355\u91CC`);
  }
  try {
    execFileSync("dsh", ["plugin", "--profile", PROFILE, "remove", pkg], {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"]
    });
  } catch {
  }
  const profile = readProfilePkg();
  const bundles = profile.dsh?.profile?.bundles;
  if (Array.isArray(bundles) && bundles.includes(pkg)) {
    profile.dsh.profile.bundles = bundles.filter((bundle) => bundle !== pkg);
    writeFileSync2(PROFILE_PKG, JSON.stringify(profile, null, 2) + "\n");
  }
  const entryId = findEntryId(loader, pkg);
  if (entryId) {
    try {
      loader.remove(entryId);
    } catch {
    }
    delete state.disabled[entryId];
  }
  delete state.disabled[pkg];
  saveState(state);
  renderPatchLayer(state);
  audit("uninstall", { pkg, entryId });
  return { pkg, removed: true, restartRequired: true };
}

// src/host/restart.ts
import { spawn } from "node:child_process";
import { mkdirSync as mkdirSync3 } from "node:fs";
import { join as join3 } from "node:path";
function relaunchArgs(argv) {
  const appArgs = [...argv.slice(2)];
  const webIndex = appArgs.indexOf("web");
  if (webIndex >= 0 && !appArgs.includes("--no-open")) {
    appArgs.splice(webIndex + 1, 0, "--no-open");
  }
  return appArgs;
}
function spawnRestart(port, argv, cwd) {
  const portArg = port || 3080;
  const logOut = join3(DATA_DIR, `restart-${Date.now()}.log`);
  const launch = {
    file: argv[0],
    args: [...process.execArgv, argv[1], ...relaunchArgs(argv)],
    cwd
  };
  const helper = [
    "const { spawn } = require('node:child_process')",
    "const fs = require('node:fs')",
    "const net = require('node:net')",
    `const launch = ${JSON.stringify(launch)}`,
    `const logOut = ${JSON.stringify(logOut)}`,
    `const port = ${JSON.stringify(portArg)}`,
    `const oldPid = ${JSON.stringify(process.pid)}`,
    'function portFree(p, cb) { const s = net.connect(p, "127.0.0.1"); s.once("connect", () => { s.destroy(); cb(false) }); s.once("error", () => cb(true)) }',
    "function waitPort(p, tries, cb) { portFree(p, (free) => { if (free || tries <= 0) cb(free); else setTimeout(() => waitPort(p, tries - 1, cb), 500) }) }",
    'setTimeout(() => { try { process.kill(oldPid, "SIGTERM") } catch {} setTimeout(() => { try { process.kill(oldPid, "SIGKILL") } catch {} }, 4000) }, 600)',
    "waitPort(port, 40, (free) => {",
    '  if (!free) { console.error("port still busy, giving up"); process.exit(1) }',
    '  const out = fs.openSync(logOut, "a")',
    '  const child = spawn(launch.file, launch.args, { cwd: launch.cwd, detached: true, stdio: ["ignore", out, out] })',
    "  child.unref()",
    "  process.exit(0)",
    "})"
  ].join("\n");
  mkdirSync3(DATA_DIR, { recursive: true });
  const child = spawn(process.execPath, ["-e", helper], { detached: true, stdio: "ignore" });
  child.unref();
  audit("restart", { logOut });
  return { restarted: true, logOut };
}

// src/host/routes.ts
function send(res, code, body) {
  const data = JSON.stringify(body);
  res.writeHead(code, {
    "content-type": "application/json; charset=utf-8",
    "content-length": Buffer.byteLength(data)
  });
  res.end(data);
}
function readBody(req) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    let size = 0;
    req.on("data", (chunk) => {
      size += chunk.length;
      if (size > 1024 * 1024) {
        reject(new Error("body too large"));
        req.destroy();
        return;
      }
      chunks.push(chunk);
    });
    req.on("end", () => {
      try {
        resolve(chunks.length ? JSON.parse(Buffer.concat(chunks).toString("utf8")) : {});
      } catch {
        reject(new Error("invalid json body"));
      }
    });
    req.on("error", reject);
  });
}
function registerRoutes(ctx, state) {
  const { loader, webServer } = ctx;
  const port = webServer.port;
  function trusted(req) {
    const remote = String(req.socket?.remoteAddress ?? "");
    if (!["127.0.0.1", "::1", "::ffff:127.0.0.1"].includes(remote)) return false;
    const origin = req.headers?.origin;
    if (typeof origin === "string" && origin !== "") {
      try {
        const url = new URL(origin);
        if (!["127.0.0.1", "localhost"].includes(url.hostname)) return false;
        if (Number(url.port) !== port) return false;
      } catch {
        return false;
      }
    }
    return true;
  }
  const list = () => ({
    ...buildList(loader, state),
    profile: PROFILE,
    dshPort: port
  });
  async function handle(req, res) {
    const sub = String(req.url ?? "").split("?")[0].slice("/my-plugins".length) || "/list";
    try {
      if (!trusted(req)) {
        audit("denied", { sub });
        return send(res, 403, { ok: false, message: "forbidden: loopback only" });
      }
      if (sub === "/list" && req.method === "GET") {
        return send(res, 200, { ok: true, ...list() });
      }
      if (sub === "/set-enabled" && req.method === "POST") {
        const body = await readBody(req);
        if (typeof body.pkg !== "string" || typeof body.enabled !== "boolean") {
          return send(res, 400, { ok: false, message: "pkg(string) and enabled(boolean) required" });
        }
        return send(res, 200, { ok: true, ...setEnabled(loader, state, body.pkg, body.enabled) });
      }
      if (sub === "/uninstall" && req.method === "POST") {
        const body = await readBody(req);
        if (typeof body.pkg !== "string") {
          return send(res, 400, { ok: false, message: "pkg(string) required" });
        }
        return send(res, 200, { ok: true, ...uninstallPackage(loader, state, body.pkg) });
      }
      if (sub === "/restart" && req.method === "POST") {
        return send(res, 200, { ok: true, ...spawnRestart(port, process.argv, process.cwd()) });
      }
      send(res, 404, { ok: false, message: "unknown endpoint" });
    } catch (error) {
      audit("error", { sub, error: String(error?.message ?? error) });
      send(res, 500, { ok: false, message: error?.message ?? String(error) });
    }
  }
  return webServer.register({ kind: "prefix", path: "/my-plugins", handler: handle });
}

// src/host/index.ts
var name = NAME;
var inject = INJECT;
function apply(ctx) {
  const host = ctx;
  if (!host || typeof host !== "object") {
    throw new Error(`${NAME}: invalid context`);
  }
  if (!host.loader) throw new Error(`${NAME}: loader service unavailable`);
  if (!host.webServer) throw new Error(`${NAME}: webServer service unavailable`);
  const state = loadState();
  const alive = /* @__PURE__ */ new Set();
  for (const entry of host.loader.entries()) {
    if (entry.options?.group) continue;
    alive.add(String(entry.id));
  }
  let changed = false;
  for (const key of Object.keys(state.disabled)) {
    if (state.disabled[key] && !alive.has(key)) {
      delete state.disabled[key];
      changed = true;
    }
  }
  if (changed) {
    saveState(state);
    renderPatchLayer(state);
  }
  return registerRoutes(host, state);
}
export {
  apply,
  inject,
  name
};
