/**
 * Build pipeline for dsh-my-plugins.
 *
 *  - src/host/**  → lib/index.js     (ESM bundle for Node; node:* builtins stay external)
 *  - src/client/** → client/client.js (single self-registering CJS payload for the
 *                                       DSH client module loader; `react` must stay a
 *                                       runtime require() inside the factory because
 *                                       the loader injects it as the factory argument)
 *
 * Both outputs are committed: consumers install the built package directly,
 * so no build step is required at install time.
 */
import { build, context } from "esbuild";

const watch = process.argv.includes("--watch");

const banner = {
  js: "// GENERATED by scripts/build.mjs — edit src/ instead of this file.",
};

const hostConfig = {
  entryPoints: ["src/host/index.ts"],
  outfile: "lib/index.js",
  bundle: true,
  platform: "node",
  format: "esm",
  target: ["node20"],
  minify: false,
  charset: "utf8",
  banner,
  logLevel: "info",
};

const clientConfig = {
  entryPoints: ["src/client/index.ts"],
  outfile: "client/client.js",
  bundle: true,
  platform: "browser",
  format: "cjs",
  target: ["es2020"],
  minify: false,
  charset: "utf8",
  banner,
  external: ["react"],
  logLevel: "info",
};

if (watch) {
  const hostCtx = await context(hostConfig);
  const clientCtx = await context(clientConfig);
  await Promise.all([hostCtx.watch(), clientCtx.watch()]);
  console.log("watching: src/host → lib/index.js · src/client → client/client.js");
} else {
  await Promise.all([build(hostConfig), build(clientConfig)]);
}